service: retorimac
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  profile: serverless-admin
  #region: us-east-2
  region: ${self:custom.regionName.${self:provider.stage}}
  stage: ${opt:stage,'TEST'}

  environment:
    REGION: ${self:provider.region}
    DYNAMO_TABLE_NAME: "${self:custom.dynamoTableName}"
    SWAPI_HOST: "swapi.py4e.com" 

# Custom Variables
custom:  
  regionName:
    TEST: us-east-2 
    us-east-2: UEAST2
  dynamoTableName: ${ssm:/reto-rimac/test/dynamo-table-name}


plugins:
  - serverless-offline

package:
  excludeDevDependencies: true
  include:
  - node_modules/**

functions:
  obtenerNombres:
    handler: src/controller/APIController.obtenerNombres
    name: ${self:custom.regionName.${self:provider.region}}COM${self:provider.stage}LAMBDASWAPI01
    description: OBTENER NOMBRES    
    events:
      - http:
          path: /challenge/personas/obtener
          method: get
          cors: true
          
  registrarNombres:
    handler: src/controller/APIController.registrarNombres
    name: ${self:custom.regionName.${self:provider.region}}COM${self:provider.stage}LAMBDASWAPI02
    description: REGISTRAR NOMBRES
    events:
      - http:
          path: /challenge/personas/registrar
          method: post
          cors: true
          request:
            parameters:
              paths:
                accion: true          
