service: retorimac
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  profile: serverless-admin
  #region: us-east-2
  region: ${self:custom.regionName.${self:provider.stage}}
  stage: ${opt:stage,'PROD'}
  apiGateway:
    shouldStartNameWithService: true

  #Environment Variables  
  environment: ${file(configuration/serverless/variables.yml)}  

# Custom Variables
custom:  
  regionName:
    PROD: us-east-1
    us-east-1: UEAST1
  dynamoTableName: ${ssm:/reto-rimac/test/dynamo-table-name}

plugins:
  - serverless-offline

package:
  excludeDevDependencies: true
  include:
  - node_modules/**

functions: ${file(configuration/serverless/functions.yml)} 
         
